### ISSUE TITLE
Setup production testing in CI

### ISSUE THREAD

**Issue by qweliant** [pubpub/platform#351]
Resolved by #658

## Motivation

 - Developers can perform e2e testing on our prod CI pipeline
 - Developers are confident that tests work against production — e.g. [Reliability ](https://github.com/orgs/pubpub/projects/46/views/1?pane=issue&itemId=57862775)
 
## Requirements

- End-to-end testing runs after PRs are created against main

## Acceptance Criteria

- Pull down the core image from ECR that was built earlier in CI.
   - Ideally this should be pulled into the same `docker-compose.test.yml` file, so we can reuse the `postgres` and `jobs` instance running there
   - You can do this with environment variables in the `docker-compose.test.yml`
- Run playwright tests against it, ideally reusing an existing docker container in e.g. the CI container.
  - You will either need to figure out how to do run Playwright tests in Alpine containers, or find an efficient way to setup yet another container.
- The possibility for the playwright  to manipulate the database should be left open.
  - Meaning that the container that runs the tests should also be able to connect to the db, use our packages etc.
 
 
 ## Extra work

**Comment by gabestein** [comment]
Still need to test in prod -- gonna just do it!
