### ISSUE TITLE
External user form editing experience for updating existing pubs

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#383]
## Motivation

So users invited to create or update pubs can do so easily and without worrying their work will be lost.

## Requirements

- Invited users can fill out form fields
- If the form is referring to an existing pub, invited users can see content that has been previously saved on the Pub
- Invited users have way to know that their work is saved that they can come back to
- Invited users can submit the form
- Invited users know their form is submitted and have an idea of what they need to do next

## Acceptance Criteria

- A url where the form can be accessed - uses the form slug and includes a param for the pub id that is being edited
- Some kind of auto-saving feedback
- Should be fairly general such that actions and action-configs could use this code to generate their forms in a future where their schemas are rewritten in json schema.
- Ensure that form URL is protected and can only be accessed with valid token
- When form is submitted it follows the behavior specified in the submission button that was clicked in #385 
- Validates form with typebox react-hook-form resolver

## Out of scope

- Markdown parsing for structural element.
- Post-form workflow/submit buttons. For now, can just have generic form save button and saved message.
- Handling requests without a pub id -- in the future, this will create a new pub. For now, it can throw an error.

## Mockups
https://www.figma.com/design/SqOTMElJn7fuPljfQL1gIY/PubPub-Platform?node-id=440-40641&t=uI7LLajjLD8aW8rH-1

**Comment by eastofesten** [comment]
> If the form is referring to an existing pub, invited users can see content that has been previously saved on the Pub

It looks like this was disabled by something committed yesterday - previously entered data from  _before_ whatever the commit is saved, but new data (or updated data) isn't.

**Comment by gabestein** [comment]
Hrm...it's possible that #687 will address this, but mind filing this as a new bug, with instructions to replicate, so we can tackle it next week? In general, I prefer that to reopening long-closed stuff.
