### ISSUE TITLE
Add ‘Edit Pub’ button to Pub page

### ISSUE THREAD

**Issue by jeffpooley** [pubpub/platform#427]
Make the UI for Community members more legible. Currently, accessing ‘Edit Pub’ is restricted to (1) the three-dot menu option on the All Pubs full-list-of-Pubs page; (2) the three-dot menu option on the Workflows/Stages view; and (3) the three-dot menu option on the Stage Manager’s per-Stage Pub tab. There is no Edit Pub affordance on the Pub page itself.

## Requirements
* Add an ‘Edit Pub’ button on the Pub page, perhaps in the upper-right-hand corner

**Comment by gabestein** [comment]
Will be addressed in #754
