### ISSUE TITLE
Add basic Pub membership UI

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#594]
## Motivation

- So admins can assign Members to individual pubs
- So admins can create reviews of pubs as children or siblings that their submitters, as contributors, can't see (relies on conceit that any form/editor that creates children will add the creator as admins of those child pubs -- seems reasonable?)
- So admins can assign editors who are responsible for managing pubs and their children without giving them deletion permissions

## Requirements

- Ability to add/remove existing community members to a Pub as an admin, contributor, or editor in the stage member tab, and invite new ones.
  - Add "add member" button to member section of the sidebar, identical to "members" page add member button
  - Only admins should see the button
  - Should repurpose the existing member add UI, e.g.:
    - When clicked, shown a popup to search by email
    - If user found, can select permission for the stage and add it
    - If no user found, sends an invitation. That invitation should use slightly different language, e.g.: `You have been invited to be a [role name] of the [stage name] stage in [community name].`
- Ability to see existing members and their role, and delete them in the member section of the pub sidebar
  - Only admins should be able to see the delete button
  - Can just be the current member list, plus their role underneath their name and an x to delete them, similar to the current pub type editor

## Acceptance Criteria
- Does not implement permissions, that's a separate card, but should add/remove the correct permissions
- Does not need to show cascading permissions yet, we can add that later

## Mockups (if available)
![Image](https://github.com/user-attachments/assets/fa3224c3-3b85-4119-b987-9a7a56c3dfe9)

<details>
  <summary>Old</summary>

Permissions behavior:
- Contributor:
  - Can see and edit pub fields
  - Can see what stage a pub is in
  - Can create child/related Pubs (they become direct members of these pubs)
  - Cannot take actions, move, or assign
- Editor: same as contributor, plus:
  - Can see and edit children and siblings (even if not directly added)
  - Can move, assign, and run actions on pubs (even if they're not stage members)
- Admin: same as editor, plus:
  - Can delete the pub
  - Can add members to the pub as contributor, editor, or community admin. (If the user does not exist, admin can invite them via email. The user receives an invitation to join PubPub as a result, with a message specifying the stage they have been invited to and a redirect to the stage configuration they have been added to.)

</details>

**Comment by 3mcd** [comment]
This all seems right to me, but I had one thought: what about adding fields to and removing fields from a pub via the UI (i.e. not via actions; including relationships)? Maybe we could restrict these types of edits to editor+.

**Comment by kalilsn** [comment]
What actions can an editor take on related pubs? The verb is missing from this requirement under editor:
>Can see and children and siblings (even if not directly added)

And since it specifies "see", does that mean that contributors of a Pub can't view its related pubs unless specifically invited?

**Comment by gabestein** [comment]
> What actions can an editor take on related pubs? The verb is missing from this requirement under editor:

See and edit!

> And since it specifies "see", does that mean that contributors of a Pub can't view its related pubs unless they're members of those pubs as well (or community editor+/stage contributor+)?

Correct. E.g. if someone is a "contributor" of a pub, we don't want them to necc. be able to see child pubs that are reviews.
