### ISSUE TITLE
Default input component for array fields

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#604]
## Motivation

So users can input an unconstrained list of things in a form.
So vector and array fields have a default input component that doesn't rely on admin configuration
So users can add multiple of unrestricted things to their pubs -- e.g., lists of DOIs or external resources

## Requirements

- Ability to input a string or a number
- Ability to add another string or number
- Ability to remove entries from the list
- Options:
   - Maximum and minimum number of items (default 0)
   - Required, which requires at least minimum number of items
   - Label
   - Maybe placeholder

## Acceptance Criteria

- Should be relatively reusable for the option interfaces for radio button and checkbox form field configuration

## Mockups 
[Multi Value Component](https://www.figma.com/design/jJIpEL3bBAHPFCHYoEPRzY/Platform-Components?node-id=608-5588&t=t2wMJw37do66Tut0-1) (open to ideas for other naming)

![Image](https://github.com/user-attachments/assets/114e32bd-3677-4b24-b22b-de14901df351)

Here is a gif demo of another component that I based my design off of. Hopefully this gives you a good idea of how I envision this working

![Image](https://github.com/user-attachments/assets/d12a2b0a-cee6-478e-8fd9-e786c17c90e0)

**Comment by allisonking** [comment]
Closed by https://github.com/pubpub/platform/pull/667
