### ISSUE TITLE
Dropdown Field Input

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#613]
## Motivation
So admins can add single-select inputs to forms for large lists of options, e.g. U.S. states.
So users can select from dropdown options on forms.

## Requirements
- For string and number field types, adds a new "Dropdown" input option.
- Field options:
  - Group description -- @ktyjscott is this the same as Help Text?
  - Ability to add individual options. Just the option value for now.
     - Option value (required) - the value stored in the pub field
     - Option name (optional) - if filled out, shows on the form instead of the value
  - Add a setting for placeholder text
  - If the input is required, the form should fail validation if the placeholder text is selected.
  - If the input is not required, no value should be created/updated for the input's corresponding pub field.
- When input field is added to form, users can select an option from a dropdown.

## Acceptance Criteria
- Add the new input component type for "Dropdown"
- Make it allowed for strings and numbers
- Add the schema for the "Dropdown" input component config form.
- Add the "Dropdown" input component config form. This form should use the multi-value component introduced in #667 for the "Dropdown Values" field.
- Add a condition to the `FormElement` component that renders a dropdown component with the options configured in the form settings.
- The options should be validated against the backing pub field's schema. For example, if the number schema is selected, the user should see an error if they try to add an alphanumeric option.
- Renders a basic dropdown on the form. Design does not need to be highly polished, can be "good enough"™ for now.

## Mockups

> Note: This mockup is a little misleading because this ticket is for fields with String and Number schemas. The mockup includes a field with a String Array schema, which is out of scope for this ticket.

[Figma Link](https://www.figma.com/design/jJIpEL3bBAHPFCHYoEPRzY/Platform-Components?node-id=118-1310&t=t2wMJw37do66Tut0-1)

![Image](https://github.com/user-attachments/assets/133877a1-2f84-4a08-9f07-8975d1a15b97)

**Comment by allisonking** [comment]
@ktyjscott we noticed that the Select dropdown has "Help Text" instead of "Description", which the checkbox group and radio group have. Is this intentional, or should they all be the same?

![Image](https://github.com/user-attachments/assets/f34303fb-82ca-46f0-b853-897bcbcdbf22)
