### ISSUE TITLE
Unjournal: remove outdated forms

### ISSUE THREAD

**Issue by eastofesten** [pubpub/platform#631]
## Motivation
Clean up the Unjournal community's unnecessary forms from testing.

## Requirements
- Re-introduce the Archive button to the community forms page.
  - There is a comment that flagposts where to do this.
- Archiving a form should move it into the "Archived" tab.
- Add an Un-archive button to the archived tab that lets a user un-archive a form.
- Slugs of archived forms are still reserved (until we add a proper delete button)
- Fill page for archived forms continue to work
- Form link directives in templates for archived forms continue to work

## Who Requested
David / Unjournal

**Comment by kalilsn** [comment]
I didn't archive unjournal's old forms but they (or we) should be able to now. LMK if I should archive them too and I can!

**Comment by eastofesten** [comment]
I can take care of it, thanks!
