### ISSUE TITLE
Admin Access to Stage Editor

### ISSUE THREAD

**Issue by eastofesten** [pubpub/platform#633]
## Motivation
For easy access to the stage editor when we open the repo.

## Requirements
- Users with admin roles on community memberships should see stage editor and settings on navbar
- Bug fix: Stage Editor tab should stay highlighted when you are on stage editor page (currently, Workflows tab is highlighted)
  - Change the URL to /stage-editor or something unique so it does not conflict with the /stages nav link
 
## Who Requested
David / Unjournal

## Optional
Currently, Editors can also add/edit the Stage Editor if they know the link -- not sure what the permissions for Stage Editor are intended to be

**Comment by 3mcd** [comment]
@ktyjscott: We agreed that the stage editor should probably be a sub-nav item beneath the Stages nav item instead of a top-level item. We also need your feedback on the icon because @kalilsn chose the icon for the stage editor somewhat arbitrarily.
