### ISSUE TITLE
Spike: Journal Article Pub Type

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#644]
## Motivation

Model an ideal "journal" Pub Type that looks like for Platform from the point of view of using Travis's editor demo to create the Pub and outputting a Pub to HTML, JATS, and PDF. Encapsulated in this motivation is the desire to avoid the shortcomings of the Legacy pub model, which put too much structure into "content," making it incredibly difficult to customize PDF and JATS output in particular. Instead, per the [Journal Article Type roadmap issue](https://github.com/orgs/pubpub/projects/46/views/1?pane=issue&itemId=72099324), we aim to map most legacy fields that could be used as metadata (and some blocks) to child/related pubs.

## Requirements

- A basic description of the structure, similar to the link roadmap issue
- A working example of a Pub in Platform that uses the proposed structure, including all needed pub types and fields, based off of [this pub](https://research.arcadiascience.com/pub/result-venom-capsids/release/1)
- An idea of how to transform Legacy prosemirror structure into new pubs, or a decision that it's too hard and we should use the existing Legacy prosemirror structure

## Acceptance Criteria

- Must be compatible with Travis' [editor demo](https://github.com/pubpub/platform/tree/tr/context-editor).
- Should start with the Journal Article Type roadmap [issue structure](https://github.com/orgs/pubpub/projects/46/views/1?pane=issue&itemId=72099324) as a jumping-off point, and justify major deviations from this structure
- Idea of what we have no concept of how to import/represent currenlty (e.g. node labels)

## Extra work

- Does not need to account for versions or release notes for now, but a good bonus if it attempts to. The default assumption is that we'll likely stuff versions into a child "version" pub whenever the pub is saved, in this way preserving all changes in a way that could be diffed, but there may be better options.
- Does not need to use actions to do any import/export. Can just use the API with local scripts that do all field mapping in code.
- Does not need to be renderable/editable in Travis's editor demo as long as Travis says the way we're conceiving of it can be compatible with it.
- To see if we can automatically import Pubs from Legacy PubPub into this structure reliably, or if we would need to flatten it some to accommodate Legacy Pubs
- A basic example of converting a Pub from the proposed structure to JATS
- An example of importing [this Pub](https://research.arcadiascience.com/pub/result-venom-capsids/release/1) from Legacy to Platform
- JATS output should validate against the [JATS4R recommendations](https://jats4r.niso.org/jats4r-validator/) for the [NISO JATS Article Publishing DTD v1.3](https://jats.nlm.nih.gov/publishing/1.3/)
- Legacy to Platform import should use the PubPub Legacy API to retrieve content from PubPub Legacy.

**Comment by 3mcd** [comment]
@gabestein Is it okay if we remove the example of converting to JATS from this spike?

**Comment by gabestein** [comment]
We're estimating ~1 day left on this! Change and let us know if that's incorrect.

**Comment by tefkah** [comment]
That seems accurate, thank you
