### ISSUE TITLE
Write function(s) that query pub or stage privilege

### ISSUE THREAD

**Issue by 3mcd** [pubpub/platform#671]
## Motivation
So developers have a way to check if a user can access or perform some action upon a pub or stage.

## Requirements

- Create a method that developers can use to determine if a community member has access to a certain resource or action.
- Function should traverse entire graph of permissions to find the highest permission at the highest level for the user (e.g. if user is a pub contributor but stage admin for the stage the current pub is in, they should have admin permissions)

## Acceptance Criteria

- A function (or functions) should be created that accepts three arguments:
  1. the platform resource (i.e. a pub or stage)
  2. a community member object
  3. some privelege associated with the resource (defined in #670)
- The function should inform the caller (e.g. by returning a boolean) of whether or not the community member has been granted permission that would authorize the requested access or action.

**Comment by kalilsn** [comment]
This is in progress (#766) but needs a little more work. Currently the query works for pub privileges, but needs to be extended for stages. I would also like to add a few more tests, but there's also an issue with the mocking of next/react functions for our tests (set up in #543) that I'm having trouble with.
