### ISSUE TITLE
Add role column to permission model

### ISSUE THREAD

**Issue by 3mcd** [pubpub/platform#672]
## Motivation

Based on the requirements defined in #594 and #595, a community member's role does not imply the level of access to resources/actions granted by permissions. Instead the permission itself conveys a role, which is not something that our permission model captures right now.

## Requirements

- Adds permissions to community, stage, and pub
- Each permission should carry a role of contributor, editor, or admin
- Includes proposal of how to move forward on migrating existing role structure iteratively into new permissions structure

## Acceptance Criteria

- Add a "role" column to the permissions table.
- Similarly to the members table, this new column stores a value of `"contributor" | "editor" | "admin"`

**Comment by kalilsn** [comment]
We've updated our approach to the membership system to #718 which will include adding the role column, to the stage/pub/community membership tables instead of the permissions table.
