### ISSUE TITLE
Inconsistent fields required for pub creation

### ISSUE THREAD

**Issue by eastofesten** [pubpub/platform#695]
### What went wrong, step-by-step?

1. User selects "Create" button to create a new pub.
2. User selects pub type for the new pub.
3. Which fields are required for a user to complete the "Create Pub" seems inconsistent (with some relation to what stage/type it is.)

### What did you expect to happen?
Either 1) all fields are required by default or 2) all fields are optional by default

## Optional
Sometimes everything is required, sometimes nothing is requires, sometimes one or two fields are required. It looks like everything is required for "No Stage"?

I think the ideal situation is to have no fields be required (users can select which fields they want to enter upon creation)?

### Have any screenshots? (Attach them by dragging the image here)
<img width="1315" alt="Screen Shot 2024-10-07 at 12 37 42 PM" src="https://github.com/user-attachments/assets/3ab1a1c8-0433-412f-a89f-440524a1cf5e">
<img width="1324" alt="Screen Shot 2024-10-07 at 12 38 06 PM" src="https://github.com/user-attachments/assets/3f0a2615-90eb-4f5e-8fed-72737b0e19ae">
<img width="1324" alt="Screen Shot 2024-10-07 at 12 38 26 PM" src="https://github.com/user-attachments/assets/fcaf3ffd-fd36-4188-9ca1-acecf6eca0ed">

**Comment by gabestein** [comment]
I think this is likely to be fixed/superseded by #754.
