### ISSUE TITLE
Add rich text input component to forms (custom and internal default)

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#721]
## Motivation
- So users can add and configure rich text fields in the form builder
- So rich text fields display by default in the internal default editor

## Requirements
- In the form builder, rich text fields can only use the "rich text" input component.
- In the default form editor, rich text fields automatically use the rich text input component.

## Acceptance Criteria
Options for form builder: 
- Label option
- Help text option (in this case, should show above the field)
- Required option

**Comment by gabestein** [comment]
@tefkah -- mind estimating when you get online tomorrow?

**Comment by tefkah** [comment]
I put 2 days. It might be faster, but I haven't really touched the form stuff much at all, so I'm expecting to run into a snag or two.
