### ISSUE TITLE
Add ability to designate a field as the title of a pubtype, both in the database and in the type editor UI

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#735]
## Motivation

- So admins can specify which field should serve as the entity name
- So developers can know which field to use as the name in locations throughout the app (e.g. pub page, API, etc.)

## Requirements

For now, we're just gonna rough this in, knowing that a full type editor redesign is planned for early next year.

- New "column" to the right of "fields" called "Name", with helper text that says: "the selected field will be used as the pub's name"
- Radio button that allows user to choose one field as the `name` field
- When creating a type, new checkbox when adding a field that says "use this field as the name field". If a name has already been selected, clicking the checkbox will overwrite the selection

## Acceptance Criteria

- Add a column to (probably?) the PubFieldToPubType table, called something like `isTitle`. If possible, it should only be possible to add one pub with `isTitle` for each PubType.
- Add a uniqueness index that guarantees that only one PubField can be marked as a title for a given PubType.
- Users can only select fields that use string, rich text, or number schemas
- A designated name field is required of all pub types
- One-time data migration that adds the designation to the first existing "title" or "name" fields; if none exists, it adds it to the first-created string, rich text, or number field; if none exists...I don't think there's one in the db, but could just create a "title" field in that case

**Comment by tefkah** [comment]
This should also add a column to (probably?) the PubFieldToPubType table, called something like "isTitle".
If possible, it should only be possible to add one pub with `isTitle` for each `PubType`. 

This might be a separate ticket.
