### ISSUE TITLE
Add ability to update and delete pub field values, including relationships, to API

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#739]
## Motivation

- So developers can work more granularly with fields in the API, including relationships

## Requirements

- Ability to update an individual field value in a pub, including a relation field
- Ability to delete relation fields from a pub

## Acceptance Criteria

- Uses utilities for updating relation fields in #764.

## Extra work

- Maybe: ability to update a related pub's relation fields? E.g. update a pub's title and also update the title of a related image in one go?

**Comment by 3mcd** [comment]
@allisonking Do you think one endpoint should handle all of this? Or one endpoint per operation, kind of like @tefkah has each relationship-related function broken out?

**Comment by gabestein** [comment]
An open question: should we do this RESTfully, or is this complicated enough that we want an RPC-style structure

**Comment by allisonking** [comment]
Although now that I'm looking at [feat: add functions to interact with relationships](https://github.com/pubpub/platform/pull/764) more, there's a [test](https://github.com/pubpub/platform/pull/764/files#diff-bc0350bb2ec87f73ca9b2dccd6b9e02e1c05c40120a8e56c203f32ce32383f6aR274) specifically to not allow updating related pub relations via the current `updatePub` function. I think this means the editor can update its own local pub, and then maybe call `updatePub` on each of its related pubs?
