### ISSUE TITLE
Fields: datetime schema defaults to YYYY-MM-DD

### ISSUE THREAD

**Issue by eastofesten** [pubpub/platform#760]
## Motivation

We currently have datetime fields that default to complete date format - `YYYY-MM-DD'T'HH:MM:SS.SSSZ` - , particularly when used as a token in emails, is not easily human-readable. These types of fields may make more sense to display in YYYY-MM-DD.

## Requirements

* Adjust default display to YYYY-MM-DD for the `DateTime` CoreSchemaTypes.

**Comment by 3mcd** [comment]
This should be as easy as updating the [`RenderWithPubPub`](https://github.com/pubpub/platform/blob/main/core/lib/server/render/pub/renderWithPubUtils.ts#L11) type to include the pub's field information (i.e. its schemas), then adding conditional to the [`visitValueDirective`](https://github.com/pubpub/platform/blob/main/core/lib/server/render/pub/renderMarkdownWithPub.ts#L35) function to format the date string if the field has the `Date` schema type.
