### ISSUE TITLE
Datacite Action

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#770]
## Motivation

So users can deposit pubs to datacite manually and automatically

## Requirements

- In configuration, allows admins to map community fields to datacite fields with validation of field type (e.g. the datacite URL field in the action should only allow mapping to a PubPub field with a string or URL schema), including the postfix
- Includes specifying which relationship field contains contributors, then specifying the pub type it will accept as a contributor, and recursively mapping fields on those types to the contributor fields
- Supports all Legacy fields
- Warns users and does not allow saving if a required datacite field is not mapped to a community field
- Allows users to deposit pubs manually and automatically
- Does not allow user to make deposit if some required fields are unfilled
- For manual deposits, warns user if deposit fails, surfacing error message from datacite to user
- For automated deposits, logs failure if a deposit does not work, surfacing error message from datacite

## Acceptance Criteria

- Pulls datacite credentials from somewhere so admins only have to enter it once (probably env vars to start)
- Uses datacite XML to generate fields for mapping, likely using [Legacy code](https://github.com/pubpub/pubpub/tree/master/deposit/datacite) as a starting point, so we can quickly update it as the datacite schema updates

## Extra work

- Automatically matches like-named community fields to datacite fields
- Allows users to register a DOI for a Pub prior to publication
- Appends short UUID to user-entered postfix to assure uniqueness
- Allows user to configure relationship types for child pubs and recursively map relationship fields

**Comment by tefkah** [comment]
One implementation suggestion: you should limit the depth you are searching the related pubs for by the path that is provided.

eg. if contributor name is to be read from `croccroc:contributors > croccroc:author > croccroc:title` , you know that `depth` in `getPubsWithRelatedValuesAndChildren` needs to be at least `4`
