### ISSUE TITLE
Datetime fields cannot be updated

### ISSUE THREAD

**Issue by eastofesten** [pubpub/platform#771]
### What went wrong, step-by-step?
two examples:

in the unjournal community:
1. User wants to update the unjournal:eval-early-deadline field in a pub.
2. User selects "Update pub" from the "[trying yet again to see if eval deadline displays"](https://app.pubpub.org/c/unjournal/pubs/eed6347c-4150-4ad8-a7be-5b25a183b0bb) Pub Card on the All Pubs Dashboard.
3. Modal appears.
4. User attempts to select datetime field value, but no option to update the field appears. 

also true (in the unjournal-demo community):
1. User creates a new field with datetime schema.
2. User adds field to existing "Submission" pubtype. 
3. User creates a new Submission via the "Create" button on the All Pubs Dashboard.
5. Datetime field shows current date, but no option to update the field appears.

### What did you expect to happen?
User can update datetime field

### What URL can we use to see the issue?
tested here: https://app.pubpub.org/c/unjournal-demo/pubs?update-pub-form=47445275-2c22-4f8d-98f9-dfce5feb2c59

### What browser/operating system were you using?
Firefox/Safari (but also reported in Chrome)

## Optional
Tried to see if this was extension-related in Firefox, but no luck. Tested in a few different communities (so it doesn't seem unjournal-specific) and a few different methods of creating/updating pubs - so definitely a browser issue. 

### Have any screenshots? (Attach them by dragging the image here)
https://github.com/user-attachments/assets/bc40e947-33e3-40e2-bc22-8eb2822b2b91

### Who reported this? (If not you)
David/Unjournal

**Comment by 3mcd** [comment]
This seems to be an issue only in Firefox. We are unable to reproduce in Chrome.
