### ISSUE TITLE
Flag and Forms Page Language For Default Form

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#781]
## Motivation
So devs can use the default form in form editing scenarios
So admins can know which form is the default and edit appropriately
So we can eventually build the ability for users to choose which form is the default

## Requirements
- The default for can be specified in the backend
- On forms page, adds a column (after name) that specifies it’s the default editor for its type.
- On form editing page, adds “Editor for this type” to the header of an individual form page, with a tooltip explaining: “This form is used as the default internal editor for all Pubs of this type.”

## Acceptance Criteria
- Does not need to implement ability to specify default form in the UI
- Add a default: boolean column on the forms table with unique index (see https://github.com/pubpub/platform/issues/782#issuecomment-2512274791)

## Design Doc
https://docs.google.com/document/d/1cWdWG1hB0b4U3ikb30U_Nd_LjvX5bANFTU2GhRqNW3s/edit?tab=t.0#heading=h.ugg1cxkdex80

**Comment by tefkah** [comment]
Should probably just include a `default: boolean` column on the forms table with unique index, see https://github.com/pubpub/platform/issues/782#issuecomment-2512274791

**Comment by tefkah** [comment]
I'd say a day as an estimeate
