### ISSUE TITLE
Create New Pub Editing Page Using Default Form

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#786]
## Motivation
So users can create and edit pubs internally using the new customizable default form.
So users have more predictable ways/places to edit pubs

## Requirements
- Ability to edit existing Pub using default form
- Ability to create new Pub using default form

### Edit and Creation
- Should show side nav, like any other page (unlike invited form `/fill` and update pages)
- Should not auto-save and should not render auto-save text in header when form is rendered on internal create or edit page
- Should warn users who navigate away without saving changes.
- For both editing and creation, form should allow user to edit the stage the pub is in, the same as the existing edit modal.
- Instead of rendering any configured submission buttons on this form, when this is an edit form, “Save” button should be placed in sticky header, aligned left with title, with the text “Form will save when you click save” next to it. When clicked, text should change to “Last saved: {time}.” 
- Should use the same permissions as the current edit and create pub modal

### Edit
- If editing a pub, should use something like `/pub/{id}/edit`, and existing values should auto-fill in the page, similar to how invited forms for existing pubs currently work
- "View Pub" button takes the place of the current "copy link" button in the top right sticky header

### Creation
- If creating a new pub, should use something like `/pub/create?type=<pubTypeID>&stage=<stageId>`. Otherwise, this can effectively be the equivalent of a current `/fill` page, with the new save button.
- No "copy link" button appears in the top right sticky header
- When a user click the save button to create the new pub, they are navigated to the edit page for the newly created pub 

## Design Doc
https://docs.google.com/document/d/1cWdWG1hB0b4U3ikb30U_Nd_LjvX5bANFTU2GhRqNW3s/edit?tab=t.0#heading=h.ugg1cxkdex80

**Comment by kalilsn** [comment]
Based on #787 I'm assuming this includes a pub creation page too, right? Should that go at `pubs/create`? And if so, it seems like there's probably another requirement to make this page use either a route or query param to set both the `type` and `stage` since they're not going to be selectable within the form anymore.

**Comment by gabestein** [comment]
Yes. I had meant to split those into two tickets, but I think someone told me it wasn't worth it. I'll add that to the ACs.

**Comment by gabestein** [comment]
I'm assuming this is 3-day for now, but it could be more and thus we may want to split out the creation page. Please let me know when you can.

**Comment by allisonking** [comment]
Let's keep it at 3-day!

**Comment by allisonking** [comment]
> If editing a pub, should use something like /pub/{id}/edit, and existing values should auto-fill in the page, similar to how invited forms for existing pubs currently work

What about for editing the stage? I know we don't want to edit a pubtype, but the current form does let you change the stage from the form, whereas the fill page does not ![Image](https://github.com/user-attachments/assets/fbf0fdee-a297-4081-b63c-73752c79fdd2)

**Comment by gabestein** [comment]
Nice catch. Yes, we should include the stage. Will add that.

**Comment by allisonking** [comment]
Closed by https://github.com/pubpub/platform/pull/821
