### ISSUE TITLE
Update Pub Creation and Editing Links To Use New Edit/Create Pages

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#787]
## Motivation
So users can create Pubs using the new create Page.
So users can more consistently access the edit page of a Pub.

## Requirements
- When user clicks add/create button (stages, workflows, workflow editor card on “Pubs tab”), they see a dropdown of the community's pub types to choose from.
- Clicking the pub type in the dropdown navigates to the fill page, which is pre-filled out with the selected type
- In the pub card hamburger menu clicking "update" loads new Pub editing page from #786.
   - Workflows
   - All pubs
   - Workflow stage settings "Pubs" panel)
- Adds "Update" button to individual pub page at the top of the sidebar, which links to new Pub editing page

## Extra Work
- Update `/fill` page to show selected stage and pub type.
- Ability to change pub type on `/fill` page

## Design Doc
https://docs.google.com/document/d/1cWdWG1hB0b4U3ikb30U_Nd_LjvX5bANFTU2GhRqNW3s/edit?tab=t.0#heading=h.ugg1cxkdex80

**Comment by tefkah** [comment]
This is in conflict with #677. I'm down for that if we really want separate update/creation pages, but I don't think we should do it for performance reasons. See the video there for some perf comparisons/comments. Sorry for not mentioning this in the doc, I thought i did but i think that was in some slack message!

We could also have the best of both worlds by using [intercepting routes](https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes). Basically, on selected pages, we would render a modal, but directly going to the url would take you to the dedicated page. I do think there is value in having modals in some places. In legacy for instance, i always found it kind of annoying how many clicks it takes to get to be able to edit a pub. This also has better performance than my approach in that PR, so i don't mind just closing that PR! For clarity: we can do the approach outlined in this issue and then add modals back with intercepted routes later, so we can just go with this.

**Comment by tefkah** [comment]
By `/fill` page you mean the `pub create` page which renders the default form here, right?
And the extra work of changing the pub type would be to facilitate creating a different kind of pub than you intended, correct? Eg I say I want to create a new "Submission", but once I'm on the page I'm like "Oh no, it should be an Evaluation instead". 

I'm clarifying bc I initially read it as "you should be able to change the pubtype of an existing pub using forms", but i don't think that's what's meant!

**Comment by tefkah** [comment]
I'd call this 2 days, even if it's quite simple, bc some e2e tests will need to be updated.

**Comment by gabestein** [comment]
> This is in conflict with https://github.com/pubpub/platform/pull/677. I'm down for that if we really want separate update/creation pages, but I don't think we should do it for performance reasons. See the video there for some perf comparisons/comments. Sorry for not mentioning this in the doc, I thought i did but i think that was in some slack message!

No worries. It's not really performance — it's mostly about making it possible to edit pubs from the pub page, and providing a more consistent experience for default pub forms, which are meant to render full-page, not in a modal. I lean moving forward with this and then later implementing intercepting routes with a modal.

> By /fill page you mean the pub create page which renders the default form here, right?
> I'm clarifying bc I initially read it as "you should be able to change the pubtype of an existing pub using forms", but i don't think that's what's meant!

Correct. This is saying you should be able to change the pub type before you create the pub, even if we move to a separate pub create page.
