### ISSUE TITLE
Create Basic New Stage Page

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#800]
## Motivation

So users can see all pubs in a stage once we limit the # of pubs displayed in the workflow page.

## Requirements

- Displays title of loaded stage and count of pubs in the stage
- Shows list of pub cards exactly the same as the current workflows page, sorted by last updated

## Acceptance Criteria

- Should re-use as much of the current workflows page as possible to reduce complexity, as this will be redesigned next year
- Url strategy of `/stages/id`, following app pattern
- Does not need to implement add pub button, though that's nice to have

## Extra work

- "Edit Stage Settings" button, only visible to admins, that opens the stage panel in the stage editor (e.g. `https://app.pubpub.org/c/<community>/stages/manage?editingStageId=<stage-id>`)
- Add button "View Stage" to stage page from  stage editor tab that links to new stage page
- Limits the page to 10 pubs and paginates the stage page on the server, exactly the same as the strategy for #778 
- Implements add pub button, with the current stage pre-selected

## Mockups (if available)
![Image](https://github.com/user-attachments/assets/197b365a-265c-4c93-b935-ece21ac7849c)

**Comment by kalilsn** [comment]
#788 is intriguing but I'm guessing you meant #778

**Comment by gabestein** [comment]
Oof. I sure did. Thanks!
